export const ProductPageLocators = {
  prodPageHeader: ".title",
  slt_Sortdropdown: ".product_sort_container",
  sort_NameAToZ: 'option[value="az"]',
  sort_NameZToA: 'option[value="za"]',
  sort_PriceLowToHigh: 'option[value="lohi"]',
  sort_PriceHighToLow: 'option[value="hilo"]',
  lst_prodLsts: ".inventory_item",
  lst_prodNames: ".inventory_item_name",
  lst_prodPrices: ".inventory_item_price",
  lst_prodDesc: ".inventory_item_desc",
  lst_btnAddToCart: ".btn.btn_small.btn_inventory",
  lst_btnRemoveCard: ".btn.btn_secondary.btn_small.btn_inventory",
  prod_prodName: ".inventory_details_name.large_size",
  prod_btnAddCart: "#add-to-cart",
  prod_btnRemove: "#remove",
  btnBackToProduct: "#back-to-products",
  iconCart: ".shopping_cart_link",
  countCartIcon: ".shopping_cart_badge",
};
